name: macOS deployment

#on: [push, pull_request]

on:
  workflow_dispatch:
  push:
     branches:
       - master

jobs:
  macos-build:
     name: MacOS Build
     strategy:
       matrix:
         os: [macos-13]

     runs-on: ${{ matrix.os }}

     steps:
     - name: Install Dependencies
       run: |
         unset HOMEBREW_NO_INSTALL_FROM_API
         brew update
         brew upgrade || true
         brew install qt6
         brew link qt6 --force
         brew install hamlib
         brew link hamlib --force
         brew install qtkeychain
         brew install dbus-glib
         brew install brotli
         brew install icu4c
         brew install pkg-config
         brew install automake
         brew install autoconf
         brew install libtool
         brew install libusb-compat
         
     - name: Checkout Code
       uses: actions/checkout@v4
       with:
         fetch-depth: 0
         submodules: recursive
     - name: Checkout Code
       uses: actions/checkout@v4
       with:
         repository: hamlib/hamlib
         path: ./hamlib
         
     - name: Configure and compile
       run: |
         cd ./hamlib
         ./bootstrap
         ./configure --prefix=/Users/runner/work/QLog/QLog/hamlib
         make -j 4
         make check
         make install
     - name: Get version from tag
       run : |
         TAGVERSION=$(git describe --tags)
         echo "TAGVERSION=${TAGVERSION:1}" >> $GITHUB_ENV

     - name: Configure and compile
       run: |
         mkdir build
         cd build
         qmake "HAMLIBINCLUDEPATH = /Users/runner/work/QLog/QLog/hamlib/include" "HAMLIBLIBPATH = /Users/runner/work/QLog/QLog/hamlib/lib" "HAMLIBVERSION_MAJOR = 4" "HAMLIBVERSION_MINOR = 6" "HAMLIBVERSION_PATCH = 0" -config release ..
         make -j4
     - name: Build dmg
       run: |
         cd build
         macdeployqt qlog.app -executable=./qlog.app/Contents/MacOS/qlog 
         macdeployqt qlog.app -dmg
     - name: Copy artifact
       uses: actions/upload-artifact@v4
       with:
         name: QLog-${{ env.TAGVERSION }}-${{ matrix.os }}
         path: /Users/runner/work/QLog/QLog/build/qlog.dmg

